// Skill options for profiles and hackathons
export const SKILL_OPTIONS = [
  'React',
  'Next.js',
  'TypeScript',
  'JavaScript',
  'Python',
  'Node.js',
  'Express',
  'Django',
  'Flask',
  'FastAPI',
  'Go',
  'Rust',
  'Java',
  'Kotlin',
  'Swift',
  'Flutter',
  'React Native',
  'Vue.js',
  'Angular',
  'Svelte',
  'TailwindCSS',
  'CSS',
  'HTML',
  'PostgreSQL',
  'MySQL',
  'MongoDB',
  'Redis',
  'GraphQL',
  'REST API',
  'Docker',
  'Kubernetes',
  'AWS',
  'GCP',
  'Azure',
  'Firebase',
  'Supabase',
  'Machine Learning',
  'Deep Learning',
  'TensorFlow',
  'PyTorch',
  'Computer Vision',
  'NLP',
  'Data Science',
  'Blockchain',
  'Solidity',
  'Web3',
  'Figma',
  'UI/UX Design',
  'Git',
  'CI/CD',
] as const;

export const EDUCATION_OPTIONS = [
  { value: 'btech', label: 'B.Tech' },
  { value: 'bca', label: 'BCA' },
  { value: 'mca', label: 'MCA' },
  { value: 'bsc', label: 'B.Sc' },
  { value: 'msc', label: 'M.Sc' },
  { value: 'other', label: 'Other' },
] as const;

export const HACKATHON_SOURCES = {
  mlh: { name: 'MLH', color: 'badge-mlh' },
  devfolio: { name: 'Devfolio', color: 'badge-devfolio' },
  unstop: { name: 'Unstop', color: 'badge-unstop' },
  devpost: { name: 'Devpost', color: 'badge-devpost' },
  community: { name: 'Community', color: 'badge-community' },
} as const;

export const HACKATHON_MODES = {
  online: { label: 'Online', icon: '🌐' },
  offline: { label: 'Offline', icon: '📍' },
  hybrid: { label: 'Hybrid', icon: '🔀' },
} as const;
